import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let d = new Date().toString();
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-800`}>
        {/* <div>{d}</div> */}

        {/* <nav className="space-x-8 p-20">
          <Link href="/posts-1">1</Link>
          <Link href="/posts-2">2</Link>
        </nav> */}
        {children}
      </body>
    </html>
  );
}
